// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl5c6cqvqFbpQHzUBWm9A7UrSg80EEgjM',
    appId: '1:891973513760:web:68f157aa699e4bbc7a0245',
    messagingSenderId: '891973513760',
    projectId: 'myfirstproject-fb20a',
    authDomain: 'myfirstproject-fb20a.firebaseapp.com',
    storageBucket: 'myfirstproject-fb20a.firebasestorage.app',
    measurementId: 'G-6TR7K5BSH8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNVq6aGuXy-YomnZvSHgnGiFI25QeZlKQ',
    appId: '1:891973513760:ios:259920e6e3ae15367a0245',
    messagingSenderId: '891973513760',
    projectId: 'myfirstproject-fb20a',
    storageBucket: 'myfirstproject-fb20a.firebasestorage.app',
    iosClientId: '891973513760-dhcii9o4jc89ebo9coaj9avm9liqsosr.apps.googleusercontent.com',
    iosBundleId: 'com.example.file',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl5c6cqvqFbpQHzUBWm9A7UrSg80EEgjM',
    appId: '1:891973513760:web:f76b7d99a25f03ad7a0245',
    messagingSenderId: '891973513760',
    projectId: 'myfirstproject-fb20a',
    authDomain: 'myfirstproject-fb20a.firebaseapp.com',
    storageBucket: 'myfirstproject-fb20a.firebasestorage.app',
    measurementId: 'G-7QMV7E89TW',
  );

}